name: Build and Release igloo_driver modules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: rehosting-arc
    steps:
      - name: Checkout igloo_driver
        uses: actions/checkout@v4
      
      - name: Trust Harbor's self-signed certificate
        run: |
          echo "Fetching certificate from ${{ secrets.REHOSTING_ARC_REGISTRY }}"
          openssl s_client -showcerts -connect ${{ secrets.REHOSTING_ARC_REGISTRY }}:443 < /dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/harbor.crt > /dev/null
          sudo update-ca-certificates
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.REHOSTING_ARC_REGISTRY }}"]
              insecure = true
              http = true

      - name: Log in to Rehosting Arc Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.REHOSTING_ARC_REGISTRY}}
          username: ${{ secrets.REHOSTING_ARC_REGISTRY_USER }}
          password: ${{ secrets.REHOSTING_ARC_REGISTRY_PASSWORD }}
      
      # Build this first, build.sh will use it later
      - name: Build kernel_builder docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder:${{ github.ref_name }}
            ${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder:latest
          build-args: |
            REGISTRY=${{ secrets.REHOSTING_ARC_REGISTRY }}/proxy
          cache-from: |
            type=registry,ref=${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder:cache,mode=max
            type=registry,ref=${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder:cache-PR-${{github.event.number}},mode=max
          cache-to: |
            type=registry,ref=${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder:cache,mode=max
            type=registry,ref=${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder:cache-PR-${{ github.event.number }}
          outputs: type=docker

      - name: Tag kernel_builder docker image
        run: |
          docker tag ${{secrets.REHOSTING_ARC_REGISTRY}}/rehosting/igloo_driver_builder igloo_driver_builder

      - name: Download kernel-devel-all from release if not present
        if: always()
        run: |
          if [ ! -f local_packages/kernel-devel-all.tar.gz ]; then
            mkdir -p local_packages
            curl -L -o local_packages/kernel-devel-all.tar.gz "https://github.com/rehosting/linux_builder/releases/latest/download/kernel-devel-all.tar.gz"
          fi
      - name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y pigz

      - name: Extract and build all modules
        run: |
          ./build.sh --versions "6.13"

      - name: Upload all built modules and symbols (always)
        uses: actions/upload-artifact@v4
        with:
          name: igloo-modules-all
          path: igloo_driver.tar.gz

      - name: Get next version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true

      - name: Create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
          name: Release ${{ steps.version.outputs.v-version }}
          body: |
            Release ${{ steps.version.outputs.v-version }}
          draft: false
          generate_release_notes: true
          prerelease: false
          files: igloo_driver.tar.gz
