name: Build and Release igloo_driver modules

on:
  push:
    branches: [main]
    tags:
      - 'dev_*'
  workflow_dispatch:

jobs:
  build:
    runs-on: rehosting-arc
    steps:
      - name: Checkout igloo_driver
        uses: actions/checkout@v4
      
      - name: Trust Harbor's self-signed certificate
        run: |
          echo "Fetching certificate from ${{ secrets.REHOSTING_ARC_REGISTRY }}"
          openssl s_client -showcerts -connect ${{ secrets.REHOSTING_ARC_REGISTRY }}:443 < /dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/harbor.crt > /dev/null
          sudo update-ca-certificates
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.REHOSTING_ARC_REGISTRY }}"]
              insecure = true
              http = true

      - name: Log in to Rehosting Arc Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.REHOSTING_ARC_REGISTRY}}
          username: ${{ secrets.REHOSTING_ARC_REGISTRY_USER }}
          password: ${{ secrets.REHOSTING_ARC_REGISTRY_PASSWORD }}

      - name: Download kernel-devel-all from release if not present
        run: |
          if [ ! -f local_packages/kernel-devel-all.tar.gz ]; then
            mkdir -p local_packages
            curl -L -o local_packages/kernel-devel-all.tar.gz "https://github.com/rehosting/linux_builder/releases/latest/download/kernel-devel-all.tar.gz"
          fi
      - name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y pigz

      - name: Extract and build all modules
        run: |
          ./build.sh --versions "4.10 6.13" \
            --image ${{secrets.REHOSTING_ARC_REGISTRY}}/proxy/rehosting/embedded-toolchains:latest \
            --release

      - name: Upload all built modules and symbols (always)
        uses: actions/upload-artifact@v4
        with:
          name: igloo-modules-all
          path: igloo_driver.tar.gz

      - name: Get next version
        if: |
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/dev_'))
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true

      - name: Create release
        if: |
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/dev_'))
        uses: softprops/action-gh-release@v2.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
          name: Release ${{ steps.version.outputs.v-version }}
          body: |
            Release ${{ steps.version.outputs.v-version }}
          draft: false
          generate_release_notes: true
          prerelease: false
          files: igloo_driver.tar.gz
